/**
 * AUTO-GENERATED — do not edit manually.
 * Run `npm run gallery` to regenerate from gallery-source/<category>/ files
 * or to refresh placeholder images.
 *
 * To use real photos:
 *   1. Place JPG/JPEG/PNG files in gallery-source/<category>/
 *   2. Run: npm run gallery
 */

export type GalleryPhotoRaw = {
  category: string;
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const galleryPhotos = [
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-01.jpg",
    width: 800,
    height: 1000,
    alt: "Rodinné focení v Plzni — Rodina při společném výletu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDKxzq1qwXzqFrwpxqVL1pejtUuVjT9IrogAD//2Q==",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-02.jpg",
    width: 800,
    height: 1200,
    alt: "Rodinné focení v Plzni — Rodinný portrét v přírodě",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDOguCxE0Stx+j7OR0PaZSiKYpFXVZIP//Z",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-03.jpg",
    width: 1200,
    height: 800,
    alt: "Rodinné focení v Plzni — Dětský smích a radost",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDJxVLWR8jLUrYDyQKcdQq9dwpT/9k=",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-04.jpg",
    width: 1600,
    height: 900,
    alt: "Rodinné focení v Plzni — Rodinné objetí a teplo domova",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGhAAAgIDAAAAAAAAAAAAAAAAAAECAxEiMf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDFWouW3MCxRUteYIAMt//Z",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-05.jpg",
    width: 900,
    height: 900,
    alt: "Rodinné focení v Plzni — Spontánní rodinný moment",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAYEAEBAQEBAAAAAAAAAAAAAAABAwIAMf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCcnM2KrykzGRF95OhjKI8pQ3kAfeOS/9k=",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-06.jpg",
    width: 800,
    height: 1000,
    alt: "Rodinné focení v Plzni — Portréty v přirozeném světle",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDDjnVrVgvnULXhTjUqXrS9HapcrGn6TKUAAB//2Q==",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-07.jpg",
    width: 1200,
    height: 800,
    alt: "Rodinné focení v Plzni — Rodinná procházka Plzní",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDOxVLWR8jLUrYDyTFOOoVeu4Qp/9k=",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-08.jpg",
    width: 800,
    height: 1200,
    alt: "Rodinné focení v Plzni — Vzácné okamžiky rodinného života",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDPAuCxE0Svx+j7OR0PaZSgKYpFXVZIP//Z",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-01.jpg",
    width: 800,
    height: 1000,
    alt: "Realitní fotografie v Plzni — Světlý obývací pokoj s moderním interiérem",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFwABAAMAAAAAAAAAAAAAAAAAAAIDBv/EABkQAAMBAQEAAAAAAAAAAAAAAAABAhEDIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AyUc6tasF86ha8J8alS9aXo7VLlY0/SqakAAf/9k=",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-02.jpg",
    width: 800,
    height: 1200,
    alt: "Realitní fotografie v Plzni — Kuchyně s otevřeným prostorem",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDLAuCxE0Svx+j7OR0PaqaApikVdVkg/9k=",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-03.jpg",
    width: 1200,
    height: 800,
    alt: "Realitní fotografie v Plzni — Ložnice s elegantním designem",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDOYql7I+RlqVsB5IFOOoVeu4o3/9k=",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-04.jpg",
    width: 1600,
    height: 900,
    alt: "Realitní fotografie v Plzni — Koupelna s přírodními materiály",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGRAAAgMBAAAAAAAAAAAAAAAAABEBAgMi/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AMrlFZv0khrFYvykiAKN/9k=",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-05.jpg",
    width: 900,
    height: 900,
    alt: "Realitní fotografie v Plzni — Prostorná terasa s výhledem",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAYEAEBAQEBAAAAAAAAAAAAAAABAwIAMf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCBOZsVXlJmMiL7ydDGUR5ShvIA+8g3/9k=",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-06.jpg",
    width: 800,
    height: 1000,
    alt: "Realitní fotografie v Plzni — Detail interiéru nemovitosti",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFwABAAMAAAAAAAAAAAAAAAAAAAIDBv/EABkQAAMBAQEAAAAAAAAAAAAAAAABAhEDIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Ay8c6tasF86ha8J8alS9aXo7VLlY0/SqakAAf/9k=",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-07.jpg",
    width: 1200,
    height: 800,
    alt: "Realitní fotografie v Plzni — Vstupní hala moderního bytu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECBv/EABoQAQACAwEAAAAAAAAAAAAAAAEAAgMRMVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzeKpeyPkWWpWwHkgU46gq9dxRP/Z",
  },
  {
    category: "reality",
    src: "/gallery/reality/reality-08.jpg",
    width: 800,
    height: 1200,
    alt: "Realitní fotografie v Plzni — Pracovní kout s přirozeným osvětlením",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDJAuCxE0Stx+j7OR0PaqSIpikVdVkg/9k=",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-01.jpg",
    width: 800,
    height: 1000,
    alt: "Příroda a krajina v okolí Plzně — Zlaté světlo při západu slunce",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFwABAAMAAAAAAAAAAAAAAAAAAAIDBv/EABkQAAMBAQEAAAAAAAAAAAAAAAABAhEDIf/EABYBAQEBAAAAAAAAAAAAAAAAAAACA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AMhHOrWrBfOoWvCfGpUvWl6O1S5WNP0hkpAAH//Z",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-02.jpg",
    width: 800,
    height: 1200,
    alt: "Příroda a krajina v okolí Plzně — Mlha nad ranní krajinou Plzeňska",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AyoLgsRNEr8fo+zkdD2higKYpFXVZIP/Z",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-03.jpg",
    width: 1200,
    height: 800,
    alt: "Příroda a krajina v okolí Plzně — Lesní stezka v podzimních barvách",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDP4ql7I+RlqVsB5IFOOoVeu4QX/9k=",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-04.jpg",
    width: 1600,
    height: 900,
    alt: "Příroda a krajina v okolí Plzně — Vodní hladina reflektující oblohu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGRAAAgMBAAAAAAAAAAAAAAAAABEBAgMi/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AMXKKzfpJDWKxflJEAEL/9k=",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-05.jpg",
    width: 900,
    height: 900,
    alt: "Příroda a krajina v okolí Plzně — Pole s dramatickými mraky",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAYEAEBAQEBAAAAAAAAAAAAAAABAwIAMf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AlZzNiq8pMxkRfeToYyiPKUN5AH3gk//Z",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-06.jpg",
    width: 800,
    height: 1000,
    alt: "Příroda a krajina v okolí Plzně — Stromová alej v ranním oparu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDNRzq1qwXzqFrwpxqVL1pejtUuVjT9JoogAD//2Q==",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-07.jpg",
    width: 1200,
    height: 800,
    alt: "Příroda a krajina v okolí Plzně — Jarní rozkvět v okolí Plzně",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDBxVLWR8jLUrYDyQKcdQq9dwgv/9k=",
  },
  {
    category: "priroda",
    src: "/gallery/priroda/priroda-08.jpg",
    width: 800,
    height: 1200,
    alt: "Příroda a krajina v okolí Plzně — Romantická zimní krajina",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDJguCxE0Svx+j7OR0PaaKApikVdVkg/9k=",
  },
] as const satisfies GalleryPhotoRaw[];
