/**
 * AUTO-GENERATED — do not edit manually.
 * Run `npm run gallery` to regenerate from gallery-source/<category>/ files
 * or to refresh placeholder images.
 *
 * To use real photos:
 *   1. Place JPG/JPEG/PNG files in gallery-source/<category>/
 *   2. Run: npm run gallery
 */

export type GalleryPhotoRaw = {
  category: string;
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const galleryPhotos = [
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-01.jpg",
    width: 800,
    height: 1000,
    alt: "Rodinné focení v Plzni — Rodina při společném výletu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDKxzq1qwXzqFrwpxqVL1pejtUuVjT9IrogAD//2Q==",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-02.jpg",
    width: 800,
    height: 1200,
    alt: "Rodinné focení v Plzni — Rodinný portrét venku",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDOguCxE0Stx+j7OR0PaZSiKYpFXVZIP//Z",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-03.jpg",
    width: 1200,
    height: 800,
    alt: "Rodinné focení v Plzni — Dětský smích a radost",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDJxVLWR8jLUrYDyQKcdQq9dwpT/9k=",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-04.jpg",
    width: 1600,
    height: 900,
    alt: "Rodinné focení v Plzni — Rodinné objetí a teplo domova",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGhAAAgIDAAAAAAAAAAAAAAAAAAECAxEiMf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDFWouW3MCxRUteYIAMt//Z",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-05.jpg",
    width: 900,
    height: 900,
    alt: "Rodinné focení v Plzni — Spontánní rodinný moment",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAYEAEBAQEBAAAAAAAAAAAAAAABAwIAMf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCcnM2KrykzGRF95OhjKI8pQ3kAfeOS/9k=",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-06.jpg",
    width: 800,
    height: 1000,
    alt: "Rodinné focení v Plzni — Portréty v přirozeném světle",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDDjnVrVgvnULXhTjUqXrS9HapcrGn6TKUAAB//2Q==",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-07.jpg",
    width: 1200,
    height: 800,
    alt: "Rodinné focení v Plzni — Rodinná procházka Plzní",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDOxVLWR8jLUrYDyTFOOoVeu4Qp/9k=",
  },
  {
    category: "rodina",
    src: "/gallery/rodina/rodina-08.jpg",
    width: 800,
    height: 1200,
    alt: "Rodinné focení v Plzni — Vzácné okamžiky rodinného života",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDPAuCxE0Svx+j7OR0PaZSgKYpFXVZIP//Z",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-01.jpg",
    width: 800,
    height: 1000,
    alt: "Svatební fotografie v Plzni — Svatební pár v objetí",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFwABAAMAAAAAAAAAAAAAAAAAAAIDBv/EABkQAAMBAQEAAAAAAAAAAAAAAAABAhEDIf/EABYBAQEBAAAAAAAAAAAAAAAAAAACA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANtHOrWrBfOoWvCfGpUvWl6O1S5WNP0yWpAAH//Z",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-02.jpg",
    width: 800,
    height: 1200,
    alt: "Svatební fotografie v Plzni — Detail svatebních prstenů",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDWguCxE0Svx+j7OR0PaKiApikVdVkg/9k=",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-03.jpg",
    width: 1200,
    height: 800,
    alt: "Svatební fotografie v Plzni — Nevěsta před obřadem",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A3WKpayPkZalbAeSBTjqFXruSN//Z",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-04.jpg",
    width: 1600,
    height: 900,
    alt: "Svatební fotografie v Plzni — První tanec novomanželů",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGRAAAgMBAAAAAAAAAAAAAAAAAAECAyIx/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANZWk5a4LElLPCACR//Z",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-05.jpg",
    width: 900,
    height: 900,
    alt: "Svatební fotografie v Plzni — Svatební hosté a emoce",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAYEAEBAQEBAAAAAAAAAAAAAAABAgMAEf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AtM8yxVeaZkgi8zskRHmllHgPSN//2Q==",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-06.jpg",
    width: 800,
    height: 1000,
    alt: "Svatební fotografie v Plzni — Romantický moment novomanželů",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDdxzq1qwXzqFrwpxqVL1pejtUuVjT9JKIgAD//2Q==",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-07.jpg",
    width: 1200,
    height: 800,
    alt: "Svatební fotografie v Plzni — Výzdoba svatebního stolu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1WKpayPkZalbAeSBTjqFXruSN//Z",
  },
  {
    category: "svatby",
    src: "/gallery/svatby/svatby-08.jpg",
    width: 800,
    height: 1200,
    alt: "Svatební fotografie v Plzni — Skupinové foto na svatbě",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2YLgsRNErcfo+zkdD2yWiKYpFXVZIP/Z",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-01.jpg",
    width: 800,
    height: 1000,
    alt: "Focení události v Plzni — Oslava narozenin v plném proudu",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAZEAADAQEBAAAAAAAAAAAAAAAAAQIRAyH/xAAVAQEBAAAAAAAAAAAAAAAAAAAABf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AIRzq1qwXzqFrwpxqVL1pejtUuVjT9JimiAAP//Z",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-02.jpg",
    width: 800,
    height: 1200,
    alt: "Focení události v Plzni — Křtiny — první rodinná fotka",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAZEAEBAQADAAAAAAAAAAAAAAABADEEMnH/xAAVAQEBAAAAAAAAAAAAAAAAAAAABf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AALgsRNEr8fo+zkdD2lqaApikVdVkg//2Q==",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-03.jpg",
    width: 1200,
    height: 800,
    alt: "Focení události v Plzni — Firemní akce a společná nálada",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDFiqWsj5GWpWwHkgU46hV67hxJ/9k=",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-04.jpg",
    width: 1600,
    height: 900,
    alt: "Focení události v Plzni — Reportáž z rodinné oslavy",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGRAAAgMBAAAAAAAAAAAAAAAAAAECAyIx/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANdaTlrgsSUs8IASTf/Z",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-05.jpg",
    width: 900,
    height: 900,
    alt: "Focení události v Plzni — Spontánní moment společenské akce",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAYEAEBAQEBAAAAAAAAAAAAAAABAwIAMf/EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCeczYqvKTMZEX3k6GBEeUobyAPvGk3/9k=",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-06.jpg",
    width: 800,
    height: 1000,
    alt: "Focení události v Plzni — Detaily výzdoby a prostředí akce",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMB/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDI51a1YL51C14U41Kl60vR2qXKxp+ktTQAAH//2Q==",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-07.jpg",
    width: 1200,
    height: 800,
    alt: "Focení události v Plzni — Skupinové foto na oslavě",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDPxVLWR8jLUrYDyQKcdQq9dw4k/9k=",
  },
  {
    category: "udalosti",
    src: "/gallery/udalosti/udalosti-08.jpg",
    width: 800,
    height: 1200,
    alt: "Focení události v Plzni — Radostné okamžiky ze slavnostní události",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMC/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDYLgsRNEr8fo+zkdD2lKaApikVdVkg/9k=",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-01.jpg",
    width: 800,
    height: 1000,
    alt: "Letecký snímek z dronu — Plzeňsko — Letecký pohled na Plzeň",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFwABAAMAAAAAAAAAAAAAAAAAAAIDBf/EABkQAAMBAQEAAAAAAAAAAAAAAAABAhEDIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAE/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AwI51a1YL51C14T41Kl60vR2qXKxp+lSFSAAP/9k=",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-02.jpg",
    width: 800,
    height: 1200,
    alt: "Letecký snímek z dronu — Plzeňsko — Krajina Plzeňska z ptačí perspektivy",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDEBcFiJolfj9H2cjoe1aBAUxSKuqyQf//Z",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-03.jpg",
    width: 1200,
    height: 800,
    alt: "Letecký snímek z dronu — Plzeňsko — Letecký snímek venkovní akce",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDN4ql7I+RlqVsB5IFOOoVeu4oJ/9k=",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-04.jpg",
    width: 1600,
    height: 900,
    alt: "Letecký snímek z dronu — Plzeňsko — Drone pohled na místo konání",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGRAAAgMBAAAAAAAAAAAAAAAAABEBAgMi/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDMyis36SQ1isX5SRAFp7//2Q==",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-05.jpg",
    width: 900,
    height: 900,
    alt: "Letecký snímek z dronu — Plzeňsko — Vzdušný záběr přírody Plzeňska",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAYEAEBAQEBAAAAAAAAAAAAAAABAwIAMf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCJOZsVXlJmMiL7ydDGUR5ShvIA+8oB/9k=",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-06.jpg",
    width: 800,
    height: 1000,
    alt: "Letecký snímek z dronu — Plzeňsko — Letecká panorama města",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAUABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRAAAwEBAQAAAAAAAAAAAAAAAAECEQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDLxzq1qwXzqFrwpxqVL1pejtUuVjT9KUaIAA//2Q==",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-07.jpg",
    width: 1200,
    height: 800,
    alt: "Letecký snímek z dronu — Plzeňsko — Dron nad krajinou za soumraku",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAGhABAAIDAQAAAAAAAAAAAAAAAQACAxExUf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AwYqlrI+RlqVsB5IFOOoVeu4xOf/Z",
  },
  {
    category: "dron",
    src: "/gallery/dron/dron-08.jpg",
    width: 800,
    height: 1200,
    alt: "Letecký snímek z dronu — Plzeňsko — Letecký detail architektonické dominanty",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAQEAAwAAAAAAAAAAAAAAAQAxBDJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDNguCxE0Svx+j7OR0PapCgKYpFXVZIP//Z",
  },
] as const satisfies GalleryPhotoRaw[];
